package com.tagora.app.theme.presets

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.tagora.app.theme.PresetTheme

/** 森林绿色主题 */
val ForestTheme = PresetTheme(
    id = "forest",
    name = "森林",
    lightScheme = lightColorScheme(
        primary = Color(0xFF2E7D32),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFB7F0B0),
        onPrimaryContainer = Color(0xFF002204),
        secondary = Color(0xFF526350),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFD5E8D0),
        onSecondaryContainer = Color(0xFF101F10),
        tertiary = Color(0xFF38656D),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFBCEBF4),
        onTertiaryContainer = Color(0xFF001F24),
        background = Color(0xFFF7FBF2),
        onBackground = Color(0xFF181D17),
        surface = Color(0xFFF7FBF2),
        onSurface = Color(0xFF181D17),
        surfaceVariant = Color(0xFFDDE5D9),
        onSurfaceVariant = Color(0xFF424940),
        surfaceContainerHighest = Color(0xFFD7E0D3),
        surfaceContainerHigh = Color(0xFFDFE8DB),
        surfaceContainer = Color(0xFFE6EFE2),
        surfaceContainerLow = Color(0xFFEDF5E9),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceDim = Color(0xFFCED6CA),
        surfaceBright = Color(0xFFF7FBF2),
        error = Color(0xFFB3261E),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFF9DEDC),
        onErrorContainer = Color(0xFF410E0B),
        outline = Color(0xFF727970),
        outlineVariant = Color(0xFFC1C9BE),
        inverseSurface = Color(0xFF2D322C),
        inverseOnSurface = Color(0xFFEEF3EA),
        inversePrimary = Color(0xFF9CD496),
        scrim = Color(0xFF000000),
    ),
    darkScheme = darkColorScheme(
        primary = Color(0xFF9CD496),
        onPrimary = Color(0xFF00390D),
        primaryContainer = Color(0xFF16531C),
        onPrimaryContainer = Color(0xFFB7F0B0),
        secondary = Color(0xFFB9CCB5),
        onSecondary = Color(0xFF253424),
        secondaryContainer = Color(0xFF3B4B39),
        onSecondaryContainer = Color(0xFFD5E8D0),
        tertiary = Color(0xFFA0CFD8),
        onTertiary = Color(0xFF00363E),
        tertiaryContainer = Color(0xFF1E4D55),
        onTertiaryContainer = Color(0xFFBCEBF4),
        background = Color(0xFF10140F),
        onBackground = Color(0xFFDEE3DA),
        surface = Color(0xFF10140F),
        onSurface = Color(0xFFDEE3DA),
        surfaceVariant = Color(0xFF424940),
        onSurfaceVariant = Color(0xFFC1C9BE),
        surfaceContainerHighest = Color(0xFF2C312A),
        surfaceContainerHigh = Color(0xFF212620),
        surfaceContainer = Color(0xFF171C16),
        surfaceContainerLow = Color(0xFF10140F),
        surfaceContainerLowest = Color(0xFF080C07),
        surfaceDim = Color(0xFF10140F),
        surfaceBright = Color(0xFF363A34),
        error = Color(0xFFF2B8B5),
        onError = Color(0xFF601410),
        errorContainer = Color(0xFF8C1D18),
        onErrorContainer = Color(0xFFF9DEDC),
        outline = Color(0xFF8C9389),
        outlineVariant = Color(0xFF424940),
        inverseSurface = Color(0xFFDEE3DA),
        inverseOnSurface = Color(0xFF2D322C),
        inversePrimary = Color(0xFF2E7D32),
        scrim = Color(0xFF000000),
    ),
)
