package com.tagora.app.theme.presets

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.tagora.app.theme.PresetTheme

/** 黑白灰单色主题 */
val MonochromeTheme = PresetTheme(
    id = "monochrome",
    name = "黑白",
    lightScheme = lightColorScheme(
        primary = Color(0xFF49454F),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFE7E0EC),
        onPrimaryContainer = Color(0xFF1D192B),
        secondary = Color(0xFF5C5C5C),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE0E0E0),
        onSecondaryContainer = Color(0xFF1A1A1A),
        tertiary = Color(0xFF6E6E6E),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFF5F5F5),
        onTertiaryContainer = Color(0xFF232323),
        background = Color(0xFFFEFBFF),
        onBackground = Color(0xFF1C1B1F),
        surface = Color(0xFFFEFBFF),
        onSurface = Color(0xFF1C1B1F),
        surfaceVariant = Color(0xFFE7E0EC),
        onSurfaceVariant = Color(0xFF49454F),
        surfaceContainerHighest = Color(0xFFE6E0E8),
        surfaceContainerHigh = Color(0xFFECE6EF),
        surfaceContainer = Color(0xFFF3EDF7),
        surfaceContainerLow = Color(0xFFF7F2FB),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceDim = Color(0xFFD8D2DD),
        surfaceBright = Color(0xFFFEFBFF),
        error = Color(0xFFB3261E),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFF9DEDC),
        onErrorContainer = Color(0xFF410E0B),
        outline = Color(0xFF79747E),
        outlineVariant = Color(0xFFCAC4D0),
        inverseSurface = Color(0xFF313033),
        inverseOnSurface = Color(0xFFF4EFF4),
        inversePrimary = Color(0xFFD0BCFF),
        scrim = Color(0xFF000000),
    ),
    darkScheme = darkColorScheme(
        primary = Color(0xFFCAC4D0),
        onPrimary = Color(0xFF1D192B),
        primaryContainer = Color(0xFF49454F),
        onPrimaryContainer = Color(0xFFE7E0EC),
        secondary = Color(0xFFC6C6C6),
        onSecondary = Color(0xFF2E2E2E),
        secondaryContainer = Color(0xFF444444),
        onSecondaryContainer = Color(0xFFE0E0E0),
        tertiary = Color(0xFFD6D6D6),
        onTertiary = Color(0xFF383838),
        tertiaryContainer = Color(0xFF4F4F4F),
        onTertiaryContainer = Color(0xFFF5F5F5),
        background = Color(0xFF1C1B1F),
        onBackground = Color(0xFFE6E1E5),
        surface = Color(0xFF1C1B1F),
        onSurface = Color(0xFFE6E1E5),
        surfaceVariant = Color(0xFF49454F),
        onSurfaceVariant = Color(0xFFCAC4D0),
        surfaceContainerHighest = Color(0xFF353237),
        surfaceContainerHigh = Color(0xFF2A272C),
        surfaceContainer = Color(0xFF201E22),
        surfaceContainerLow = Color(0xFF1C1B1F),
        surfaceContainerLowest = Color(0xFF0F0D13),
        surfaceDim = Color(0xFF141318),
        surfaceBright = Color(0xFF3B383E),
        error = Color(0xFFF2B8B5),
        onError = Color(0xFF601410),
        errorContainer = Color(0xFF8C1D18),
        onErrorContainer = Color(0xFFF9DEDC),
        outline = Color(0xFF938F99),
        outlineVariant = Color(0xFF49454F),
        inverseSurface = Color(0xFFE6E1E5),
        inverseOnSurface = Color(0xFF313033),
        inversePrimary = Color(0xFF49454F),
        scrim = Color(0xFF000000),
    ),
)
