package com.tagora.app.theme.presets

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.tagora.app.theme.PresetTheme

/** 海洋蓝色主题 */
val OceanTheme = PresetTheme(
    id = "ocean",
    name = "海洋",
    lightScheme = lightColorScheme(
        primary = Color(0xFF1B6CA8),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFD1E4FF),
        onPrimaryContainer = Color(0xFF001D36),
        secondary = Color(0xFF006B5E),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFF7AF8E0),
        onSecondaryContainer = Color(0xFF00201B),
        tertiary = Color(0xFF5C56D6),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFE3DFFF),
        onTertiaryContainer = Color(0xFF160362),
        background = Color(0xFFF8FDFF),
        onBackground = Color(0xFF001F25),
        surface = Color(0xFFF8FDFF),
        onSurface = Color(0xFF001F25),
        surfaceVariant = Color(0xFFDFE2EB),
        onSurfaceVariant = Color(0xFF43474E),
        surfaceContainerHighest = Color(0xFFD9E0E8),
        surfaceContainerHigh = Color(0xFFE1E8F0),
        surfaceContainer = Color(0xFFEAEFF7),
        surfaceContainerLow = Color(0xFFF1F5FC),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceDim = Color(0xFFD0D7DF),
        surfaceBright = Color(0xFFF8FDFF),
        error = Color(0xFFB3261E),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFF9DEDC),
        onErrorContainer = Color(0xFF410E0B),
        outline = Color(0xFF73777F),
        outlineVariant = Color(0xFFC3C7CF),
        inverseSurface = Color(0xFF2E3135),
        inverseOnSurface = Color(0xFFEFF4F7),
        inversePrimary = Color(0xFF9CCAFF),
        scrim = Color(0xFF000000),
    ),
    darkScheme = darkColorScheme(
        primary = Color(0xFF9CCAFF),
        onPrimary = Color(0xFF003258),
        primaryContainer = Color(0xFF00497D),
        onPrimaryContainer = Color(0xFFD1E4FF),
        secondary = Color(0xFF5DDBC5),
        onSecondary = Color(0xFF003830),
        secondaryContainer = Color(0xFF005046),
        onSecondaryContainer = Color(0xFF7AF8E0),
        tertiary = Color(0xFFC7C2FF),
        onTertiary = Color(0xFF2D238C),
        tertiaryContainer = Color(0xFF443DA4),
        onTertiaryContainer = Color(0xFFE3DFFF),
        background = Color(0xFF0E1418),
        onBackground = Color(0xFFDEE4E8),
        surface = Color(0xFF0E1418),
        onSurface = Color(0xFFDEE4E8),
        surfaceVariant = Color(0xFF43474E),
        onSurfaceVariant = Color(0xFFC3C7CF),
        surfaceContainerHighest = Color(0xFF2D3136),
        surfaceContainerHigh = Color(0xFF22262B),
        surfaceContainer = Color(0xFF181C21),
        surfaceContainerLow = Color(0xFF0E1418),
        surfaceContainerLowest = Color(0xFF070A0E),
        surfaceDim = Color(0xFF0E1418),
        surfaceBright = Color(0xFF343A3F),
        error = Color(0xFFF2B8B5),
        onError = Color(0xFF601410),
        errorContainer = Color(0xFF8C1D18),
        onErrorContainer = Color(0xFFF9DEDC),
        outline = Color(0xFF8D9199),
        outlineVariant = Color(0xFF43474E),
        inverseSurface = Color(0xFFDEE4E8),
        inverseOnSurface = Color(0xFF2E3135),
        inversePrimary = Color(0xFF1B6CA8),
        scrim = Color(0xFF000000),
    ),
)
