package com.tagora.app.theme.presets

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.tagora.app.theme.PresetTheme

/** 日落暖色主题 */
val SunsetTheme = PresetTheme(
    id = "sunset",
    name = "日落",
    lightScheme = lightColorScheme(
        primary = Color(0xFFB95C1C),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDBC9),
        onPrimaryContainer = Color(0xFF361200),
        secondary = Color(0xFF77594A),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFDBC9),
        onSecondaryContainer = Color(0xFF2C160B),
        tertiary = Color(0xFF6A5D2F),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFF4E1A7),
        onTertiaryContainer = Color(0xFF221B00),
        background = Color(0xFFFFF8F6),
        onBackground = Color(0xFF201A17),
        surface = Color(0xFFFFF8F6),
        onSurface = Color(0xFF201A17),
        surfaceVariant = Color(0xFFF4DED3),
        onSurfaceVariant = Color(0xFF52443C),
        surfaceContainerHighest = Color(0xFFEED8CE),
        surfaceContainerHigh = Color(0xFFF4E0D6),
        surfaceContainer = Color(0xFFFAE8DE),
        surfaceContainerLow = Color(0xFFFEF0E7),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceDim = Color(0xFFE4D0C6),
        surfaceBright = Color(0xFFFFF8F6),
        error = Color(0xFFB3261E),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFF9DEDC),
        onErrorContainer = Color(0xFF410E0B),
        outline = Color(0xFF84746B),
        outlineVariant = Color(0xFFD7C3B9),
        inverseSurface = Color(0xFF362F2B),
        inverseOnSurface = Color(0xFFFDEDE7),
        inversePrimary = Color(0xFFFFB68C),
        scrim = Color(0xFF000000),
    ),
    darkScheme = darkColorScheme(
        primary = Color(0xFFFFB68C),
        onPrimary = Color(0xFF562200),
        primaryContainer = Color(0xFF7A3F13),
        onPrimaryContainer = Color(0xFFFFDBC9),
        secondary = Color(0xFFE6BFA8),
        onSecondary = Color(0xFF432B1F),
        secondaryContainer = Color(0xFF5D4034),
        onSecondaryContainer = Color(0xFFFFDBC9),
        tertiary = Color(0xFFD7C58D),
        onTertiary = Color(0xFF393005),
        tertiaryContainer = Color(0xFF51461A),
        onTertiaryContainer = Color(0xFFF4E1A7),
        background = Color(0xFF18120F),
        onBackground = Color(0xFFECE0DA),
        surface = Color(0xFF18120F),
        onSurface = Color(0xFFECE0DA),
        surfaceVariant = Color(0xFF52443C),
        onSurfaceVariant = Color(0xFFD7C3B9),
        surfaceContainerHighest = Color(0xFF332B27),
        surfaceContainerHigh = Color(0xFF28201C),
        surfaceContainer = Color(0xFF1E1713),
        surfaceContainerLow = Color(0xFF18120F),
        surfaceContainerLowest = Color(0xFF0F0A07),
        surfaceDim = Color(0xFF18120F),
        surfaceBright = Color(0xFF3F3733),
        error = Color(0xFFF2B8B5),
        onError = Color(0xFF601410),
        errorContainer = Color(0xFF8C1D18),
        onErrorContainer = Color(0xFFF9DEDC),
        outline = Color(0xFFA08D84),
        outlineVariant = Color(0xFF52443C),
        inverseSurface = Color(0xFFECE0DA),
        inverseOnSurface = Color(0xFF362F2B),
        inversePrimary = Color(0xFFB95C1C),
        scrim = Color(0xFF000000),
    ),
)
